### ISSUE TITLE
logo eurodistrict

### ISSUE THREAD

**Issue by catherinemosser** [AlsaceDigitale/geeksonafarm_2015#3]
![web_logo-euro-district](https://cloud.githubusercontent.com/assets/7852945/7687426/8a58c71a-fd9d-11e4-9a51-e52b66be4dc0.jpg)

**Comment by yannski** [comment]
fixed in https://github.com/AlsaceDigitale/geeksonafarm_2015/commit/a4e9b32dbe491ef4bca7294aec77546837f5a007
